version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "npm"
    directory: "/packages/integration-tests/fixtures"
    ignore:
      - dependency-name: "*"