# It's really frustrating that we cannot get dependabot to ignore the integration test fixture
# lock files from the scans it does: https://github.com/dependabot/dependabot-core/issues/4364
#
# This workflow will auto-close any such PRs.

name: Auto-close dependabot PRs targeting integration test fixtures

on:
  pull_request:
    branches: [master]
    paths:
      - 'packages/integration-tests/fixtures/**'

jobs:
  maybe_auto_close:
    # Only run if it was dependabot that triggered the workflow
    if: contains('["dependabot[bot]"]', github.actor) == true
    name: Auto-close the PR if dependabot opened it and is targeting an integration test fixture
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Auto-close the PR
      uses: ./.github/actions/auto-close-pr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment: "Auto-closed because it targets an integration test fixture lock file. It's really frustrating that we cannot get dependabot to ignore these from the scans it does: https://github.com/dependabot/dependabot-core/issues/4364"

