name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 13
        
    - name: Install dependencies
      run: |
        # This also runs a build as part of the postinstall
        # bootstrap
        yarn --ignore-engines --frozen-lockfile

    - name: Typecheck all packages
      run: |
        # Note that this command *also* typechecks tests/tools,
        # whereas the build only checks src files
        yarn typecheck
